# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown

title: Giorgio Fellipe
BASE_PATH: 

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Giorgio Fellipe

description: De desenvolvedor para desenvolvedor
author:
  name: Giorgio Fellipe
  email: giorgiofellipe@gmail.com
  github: giorgiofellipe
  twitter: giiorgio_
  pinterest: 
  linkedin: giorgio-fellipe-cegatta-dos-santos/57/769/b94
  bio: Desenvolvedor WEB e Mobile
  email_md5: 707b4151a10bb58827fd46754700a8e3

home: giorgiofellipe.com.br

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
